doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        server_version: '14'
        charset: 'utf8'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Auth:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Security/Entity'
                prefix: 'App\Security\Entity'
                alias: Security
        query_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        result_cache_driver:
            type: pool
            pool: doctrine.result_cache_pool

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
