doctrine_migrations:
    enable_profiler: false
    migrations_paths:
        'DoctrineMigrations': '%kernel.project_dir%/migrations'

when@dev:
    doctrine_migrations:
        enable_profiler: true
