framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: false
    http_method_override: false
    handle_all_throwables: true
    session:
        enabled: false
    esi: false
    fragments: false
    php_errors:
        log: true

when@test:
    framework:
        test: true
