version: '3'

services:
  database:
    image: postgres:14-alpine3.17
    environment:
      POSTGRES_DB: symfony_clean_auth
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
    ports:
      - "5432:5432"

  store:
    image: eqalpha/keydb:alpine_x86_64_v6.3.1
    ports:
      - "6379:6379"
