version: '3'

services:
  database:
    image: postgres:14-alpine3.17
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "streaming_website" ]
      interval: 2s
      timeout: 10s
      retries: 15
    environment:
      POSTGRES_DB: streaming_website
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
    ports:
      - "5432:5432"

  mailer:
    image: schickling/mailcatcher:latest
    ports:
      - "1025:1025"
      - "1080:1080"

  store:
    image: eqalpha/keydb:alpine_x86_64_v6.3.1
    ports:
      - "6379:6379"
