services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/*.php'
            - '../src/Kernel.php'

    App\Controller\ErrorController:
        arguments: ['%kernel.environment%']

    Predis\Client:
        alias: 'snc_redis.default'
