services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\ErrorController:
        arguments: ['%kernel.environment%']

    App\Shared\Service\ServiceInterface:
        public: true

    Predis\Client:
        alias: 'snc_redis.default'
