services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/**/Entity/'
            - '../src/Kernel.php'

    _instanceof:
        App\Shared\Http\ControllerInterface:
            tags: [ 'controller.service_arguments' ]
